// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: printer.proto

package printer

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PrinterService_PrintMessage_FullMethodName = "/printer.PrinterService/PrintMessage"
)

// PrinterServiceClient is the client API for PrinterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PrinterServiceClient interface {
	PrintMessage(ctx context.Context, in *PrintRequest, opts ...grpc.CallOption) (*PrintResponse, error)
}

type printerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPrinterServiceClient(cc grpc.ClientConnInterface) PrinterServiceClient {
	return &printerServiceClient{cc}
}

func (c *printerServiceClient) PrintMessage(ctx context.Context, in *PrintRequest, opts ...grpc.CallOption) (*PrintResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrintResponse)
	err := c.cc.Invoke(ctx, PrinterService_PrintMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PrinterServiceServer is the server API for PrinterService service.
// All implementations must embed UnimplementedPrinterServiceServer
// for forward compatibility.
type PrinterServiceServer interface {
	PrintMessage(context.Context, *PrintRequest) (*PrintResponse, error)
	mustEmbedUnimplementedPrinterServiceServer()
}

// UnimplementedPrinterServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPrinterServiceServer struct{}

func (UnimplementedPrinterServiceServer) PrintMessage(context.Context, *PrintRequest) (*PrintResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PrintMessage not implemented")
}
func (UnimplementedPrinterServiceServer) mustEmbedUnimplementedPrinterServiceServer() {}
func (UnimplementedPrinterServiceServer) testEmbeddedByValue()                        {}

// UnsafePrinterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PrinterServiceServer will
// result in compilation errors.
type UnsafePrinterServiceServer interface {
	mustEmbedUnimplementedPrinterServiceServer()
}

func RegisterPrinterServiceServer(s grpc.ServiceRegistrar, srv PrinterServiceServer) {
	// If the following call pancis, it indicates UnimplementedPrinterServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PrinterService_ServiceDesc, srv)
}

func _PrinterService_PrintMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrintRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrinterServiceServer).PrintMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrinterService_PrintMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrinterServiceServer).PrintMessage(ctx, req.(*PrintRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PrinterService_ServiceDesc is the grpc.ServiceDesc for PrinterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PrinterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "printer.PrinterService",
	HandlerType: (*PrinterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PrintMessage",
			Handler:    _PrinterService_PrintMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "printer.proto",
}
