// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: printer.proto

package printer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PrintRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrintRequest) Reset() {
	*x = PrintRequest{}
	mi := &file_printer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrintRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrintRequest) ProtoMessage() {}

func (x *PrintRequest) ProtoReflect() protoreflect.Message {
	mi := &file_printer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrintRequest.ProtoReflect.Descriptor instead.
func (*PrintRequest) Descriptor() ([]byte, []int) {
	return file_printer_proto_rawDescGZIP(), []int{0}
}

func (x *PrintRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type PrintResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrintResponse) Reset() {
	*x = PrintResponse{}
	mi := &file_printer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrintResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrintResponse) ProtoMessage() {}

func (x *PrintResponse) ProtoReflect() protoreflect.Message {
	mi := &file_printer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrintResponse.ProtoReflect.Descriptor instead.
func (*PrintResponse) Descriptor() ([]byte, []int) {
	return file_printer_proto_rawDescGZIP(), []int{1}
}

func (x *PrintResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_printer_proto protoreflect.FileDescriptor

const file_printer_proto_rawDesc = "" +
	"\n" +
	"\rprinter.proto\x12\aprinter\"\"\n" +
	"\fPrintRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"'\n" +
	"\rPrintResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2O\n" +
	"\x0ePrinterService\x12=\n" +
	"\fPrintMessage\x12\x15.printer.PrintRequest\x1a\x16.printer.PrintResponseB*Z(github.com/vsevolod/grpc-printer;printerb\x06proto3"

var (
	file_printer_proto_rawDescOnce sync.Once
	file_printer_proto_rawDescData []byte
)

func file_printer_proto_rawDescGZIP() []byte {
	file_printer_proto_rawDescOnce.Do(func() {
		file_printer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_printer_proto_rawDesc), len(file_printer_proto_rawDesc)))
	})
	return file_printer_proto_rawDescData
}

var file_printer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_printer_proto_goTypes = []any{
	(*PrintRequest)(nil),  // 0: printer.PrintRequest
	(*PrintResponse)(nil), // 1: printer.PrintResponse
}
var file_printer_proto_depIdxs = []int32{
	0, // 0: printer.PrinterService.PrintMessage:input_type -> printer.PrintRequest
	1, // 1: printer.PrinterService.PrintMessage:output_type -> printer.PrintResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_printer_proto_init() }
func file_printer_proto_init() {
	if File_printer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_printer_proto_rawDesc), len(file_printer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_printer_proto_goTypes,
		DependencyIndexes: file_printer_proto_depIdxs,
		MessageInfos:      file_printer_proto_msgTypes,
	}.Build()
	File_printer_proto = out.File
	file_printer_proto_goTypes = nil
	file_printer_proto_depIdxs = nil
}
